In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import librosa

In [0]:
data=pd.read_csv("/content/drive/My Drive/ML_works/Recommendation_system/Audio_recommendation/Data_files/aawaj_sample.csv")

In [0]:
data

2019-07-16 01:06:57.428^44^First Open - User not created yet^app opened^play_release
0  2019-07-16 01:09:52.055^45^com.aawaz^49^v2.1.2...

In [0]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
2019-07-16 01:06:57.428^44^First Open - User not created yet^app opened^play_release    1 non-null object
dtypes: object(1)
memory usage: 88.0+ bytes


In [0]:
sample=data["2019-07-16 01:06:57.428^44^First Open - User not created yet^app opened^play_release"][0]

In [0]:
sample

'2019-07-16 01:09:52.055^45^com.aawaz^49^v2.1.2^android^2gf9Jfadfig67FhdQXs4Cxq2fvN2^msm8953^vivo^1723^qcom^vivo^vivo 1723^1557476533000^27^8.1.0^play_release'

In [0]:
sample.split("^")

['2019-07-16 01:09:52.055',
 '45',
 'com.aawaz',
 '49',
 'v2.1.2',
 'android',
 '2gf9Jfadfig67FhdQXs4Cxq2fvN2',
 'msm8953',
 'vivo',
 '1723',
 'qcom',
 'vivo',
 'vivo 1723',
 '1557476533000',
 '27',
 '8.1.0',
 'play_release']

In [0]:
mat=np.random.randint(3,6,(3,7))

In [0]:
from scipy.linalg import svd

In [0]:
from sklearn.decomposition import TruncatedSVD

In [0]:
fiit=TruncatedSVD(n_components=4)

In [0]:
v=fiit.fit_transform(mat)

In [34]:
v

array([[11.33147747, -1.3668655 , -1.31502739],
       [10.98601068,  2.06037781, -0.24982507],
       [ 9.91530754, -0.72077714,  1.77965071]])

In [33]:
v[1]

array([10.98601068,  2.06037781, -0.24982507])

In [0]:
u,a,v=svd(mat)

In [20]:
print(u)

[[-0.55294279  0.3558805   0.75339454]
 [-0.60973352  0.44342229 -0.65696401]
 [-0.56787262 -0.82263342 -0.02819489]]


In [21]:
print(a)

[18.67974075  2.26576068  1.71277959]


In [22]:
print(v)

[[-0.34097116 -0.34097116 -0.36833139 -0.46321546 -0.40241455 -0.34017191
  -0.3736126 ]
 [-0.19825704 -0.19825704 -0.59996549 -0.05148519  0.67465806  0.32188347
  -0.00255133]
 [-0.28051008 -0.28051008  0.52646104  0.19919565  0.23211861  0.175818
  -0.66407608]
 [-0.47203354  0.13909102 -0.29028     0.77262114 -0.21347104 -0.17494918
   0.02133126]
 [-0.53254871  0.47953291  0.24905753 -0.31009556  0.37604283 -0.40500726
   0.15103666]
 [-0.40788441  0.28149376  0.03744476 -0.22326144 -0.3760199   0.74501162
   0.08191771]
 [-0.30488264 -0.66121861  0.28198925  0.01238767 -0.02551322 -0.00904031
   0.62404525]]


In [0]:
from scipy.sparse.linalg import svds

In [0]:
mat=np.random.randint(3,8,(4,3))

In [0]:
U, sigma, V = svd(mat)

In [72]:
U

array([[-0.58849726,  0.1609398 ,  0.21047792, -0.76385103],
       [-0.48206744, -0.85108409,  0.04213983,  0.20369361],
       [-0.48673611,  0.28809169, -0.79577107,  0.21642446],
       [-0.42938317,  0.40835944,  0.56627881,  0.57288827]])

In [73]:
sigma

array([17.78902715,  3.61348562,  1.22197987])

In [74]:
V

array([[-0.62186643, -0.51012647, -0.59418274],
       [ 0.76160067, -0.21729288, -0.6105311 ],
       [ 0.18233639, -0.83219877,  0.52363981]])

In [0]:
sigma=np.diag(sigma)

In [76]:
sigma

array([[17.78902715,  0.        ,  0.        ],
       [ 0.        ,  3.61348562,  0.        ],
       [ 0.        ,  0.        ,  1.22197987]])

In [77]:
pred=np.dot(np.dot(U,sigma),V)

ValueError: ignored

In [0]:
from scipy.sparse.linalg import svds

In [79]:
U, sigma, Vt = svds(mat,k=2)

ValueError: ignored

In [0]:
mat=np.matrix(mat)

In [85]:
a,b,c=svds(mat,k=2)

ValueError: ignored

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
